In [1]:
from unicodedata import category
from datetime import datetime, timedelta
import streamlit as st
import pandas as pd
import sys
sys.path.append("src")
from database.connection import get_db, SessionLocal
from database.models import Expense
from crud_ops_aux import insert_expenses, delete_expense, get_all_expenses

ModuleNotFoundError: No module named 'database'

In [3]:
import pandas as pd

In [12]:
df = pd.read_excel("../data/export-transactions_20250207.xlsx", skiprows=4)
df = df.iloc[:, 1:]
df.head(10)

,Data,Título,Categoria,Conta,Cartão de crédito,Valor
0,02/12/2024,13o salário,renda,Keth Conta e Debito,NaN,2451.02
1,03/12/2024,iFood,alimentação,Keth Conta e Debito,NaN,-38.98
2,03/12/2024,Faxina,moradia,Keth Conta e Debito,NaN,-250.00
3,04/12/2024,a identificar,outros,Keth Conta e Debito,NaN,-95.90
4,04/12/2024,café,alimentação,Keth Conta e Debito,NaN,-12.49
5,05/12/2024,cafe,alimentação,Keth Conta e Debito,NaN,-13.50
6,06/12/2024,99,transporte,Keth Conta e Debito,NaN,-49.20
7,09/12/2024,restaurante,alimentação,Keth Conta e Debito,NaN,-121.30
8,09/12/2024,99,transporte,Keth Conta e Debito,NaN,-22.98
9,09/12/2024,estacionamento,transporte,Keth Conta e Debito,NaN,-26.00